apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
spec:
  terminationGracePeriodSeconds: 1
  serviceAccountName: service-reader # Run this pod under a different service account.
  containers:
  - name: app
    image: nigelpoulton/curl:1.0
    command: ['sh', '-c', 'sleep 9999'] # Keeps the container running.
  - name: test1
    image: nigelpoulton/k8s-api-proxy:1.0 # This is the ambassador container.

# Open bash prompt in the main container. If conatainer is
# not explicitly listed then the first container will be used.
# kubectl exec -it sa-demo bash
# > curl localhost:8001/api/v1/namespace/default/services/
# This is the service call to get services.

# List pods (which is not authorized).
# > curl localhost:8001/api/v1/namespace/default/pods/
# This will not work, a 403 response is returned.