apiVersion: v1
kind: Service
metadata:
  name: pluralsight-ftw
spec:
  selector:
    app: initializer # This service is meant for init-pod.yml.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer